### ISSUE TITLE
Disconnection/connection/reconnection problem

### ISSUE THREAD

**Issue by MaIIory** [MaIIory/summoner-wars#8]
After some specific time clients are disconnecting from the server. It may be caused by some reconnection event, socket framework issue or timeout.
Issue may be reproduced by just leaving for some time opened clients game sessions.
Proposal for solve the problem:
- set latest version of library for nodejs, express and socket. If it will not help reverse version of socket.io to 0.8.6.
- set ping/pong mechanism between server and clients to keep activity and try to avoid any timeouts.
- reconfigure client connection to server according to official documentation (reconnecton, reconnection delay and so on)

**Comment by MaIIory** [comment]
https://github.com/socketio/socket.io-client-java/issues/123 
article about how to set ping/pong mechanism

**Comment by MaIIory** [comment]
"Having the same issue...I also noticed that immediately after the socket disconnected a new socket was instantiated.

Workaround for me was manually setting the close timeout:

io.configure( function() {
    io.set('close timeout', 60_60_24); // 24h time out
}); "

**Comment by MaIIory** [comment]
https://github.com/socketio/socket.io/issues/777

**Comment by MaIIory** [comment]
heartbeat configuration:
http://stackoverflow.com/questions/20387550/websocketssocketio-preventing-heartbeat-timeout

**Comment by MaIIory** [comment]
how to set heartbeat:
http://stackoverflow.com/questions/12815231/controlling-the-heartbeat-timeout-from-the-client-in-socket-io

**Comment by MaIIory** [comment]
https://github.com/socketio/engine.io#methods-1

**Comment by fc** [comment]
saw that you linked to socketio/socket.io#777 and after skimming through your code it looks like maybe the native setTimeout is overridden and that could be the root of the issue

**Comment by MaIIory** [comment]
After long search it turned out that my application was periodically disconnecting by my service provider. The app was deployed on Heroku cloud which use something called "dynos" as container for  aplication. The free (default) settings of this dyno is just for experimental purposes and to save resources it disconnetcs app after 30 minutes.So, the solution is to pay at least 7$ per month, however - it is cloud so you can enable advenced dyno only when you need and in that case you will pay much less.
